-- AJG Builder billing access engine: per-site state, transition audit and runtime capabilities.
create table if not exists public.site_billing_states (
  site_id uuid primary key references public.sites(id) on delete cascade,
  owner_id uuid not null references auth.users(id) on delete cascade,
  state text not null default 'active' check (state in ('free','trial','active','grace','restricted','public_suspended','retention','closed')),
  provider_status text, paid_through timestamptz, grace_started_at timestamptz, grace_until timestamptz,
  restricted_at timestamptz, public_suspend_at timestamptz, export_until timestamptz, delete_after timestamptz,
  cancel_at_period_end boolean not null default false, manual_hold_reason text, updated_at timestamptz not null default now(),
  check (grace_until is null or grace_started_at is null or grace_until >= grace_started_at),
  check (public_suspend_at is null or restricted_at is null or public_suspend_at >= restricted_at),
  check (export_until is null or restricted_at is null or export_until >= restricted_at),
  check (delete_after is null or export_until is null or delete_after >= export_until)
);
alter table public.site_billing_states enable row level security;
revoke all on public.site_billing_states from anon;
revoke insert,update,delete on public.site_billing_states from authenticated;
grant select on public.site_billing_states to authenticated;
drop policy if exists "Owners can read site billing state" on public.site_billing_states;
create policy "Owners can read site billing state" on public.site_billing_states for select to authenticated using ((select auth.uid())=owner_id);

create table if not exists public.billing_state_events (
 id bigint generated by default as identity primary key, site_id uuid not null references public.sites(id) on delete cascade,
 owner_id uuid not null references auth.users(id) on delete cascade, from_state text, to_state text not null,
 reason text not null, provider_event_id text, created_at timestamptz not null default now(), unique(provider_event_id)
);
alter table public.billing_state_events enable row level security;
revoke all on public.billing_state_events from anon;
revoke insert,update,delete on public.billing_state_events from authenticated;
grant select on public.billing_state_events to authenticated;
drop policy if exists "Owners can read billing state events" on public.billing_state_events;
create policy "Owners can read billing state events" on public.billing_state_events for select to authenticated using ((select auth.uid())=owner_id);
create index if not exists billing_state_events_site_created_idx on public.billing_state_events(site_id,created_at desc);

create or replace function public.get_my_site_capabilities(p_site_id uuid)
returns table(billing_state text,can_read boolean,can_edit boolean,can_publish boolean,can_generate_ai boolean,can_import boolean,can_export boolean,can_collect_leads boolean,can_view_billing boolean,public_site_available boolean)
language sql security invoker set search_path=''
as $$
 with owned as (select s.id,s.owner_id from public.sites s where s.id=p_site_id and s.owner_id=(select auth.uid())),
 b as (select coalesce(bs.state,'active') state from owned o left join public.site_billing_states bs on bs.site_id=o.id)
 select state,
 state in ('free','trial','active','grace','restricted','public_suspended','retention'),
 state in ('free','trial','active','grace'), state in ('free','trial','active','grace'),
 state in ('free','trial','active'), state in ('free','trial','active','grace'),
 state in ('free','trial','active','grace','restricted','public_suspended','retention'),
 state in ('free','trial','active','grace'), true,
 state in ('free','trial','active','grace','restricted') from b
$$;
revoke all on function public.get_my_site_capabilities(uuid) from public,anon;
grant execute on function public.get_my_site_capabilities(uuid) to authenticated,service_role;
