-- Idempotent arrears notifications and payment recovery primitives.
create table if not exists public.billing_notifications (
 id bigint generated by default as identity primary key,
 site_id uuid not null references public.sites(id) on delete cascade,
 owner_id uuid not null references auth.users(id) on delete cascade,
 notification_key text not null check(notification_key in ('payment_failed','reminder_j3','reminder_j7','reminder_j12','retention_j74','retention_j97','reactivated')),
 due_at timestamptz not null,status text not null default 'pending' check(status in ('pending','processing','sent','failed','canceled')),
 attempts integer not null default 0,sent_at timestamptz,last_error text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),
 unique(site_id,notification_key,due_at)
);
alter table public.billing_notifications enable row level security;
revoke all on public.billing_notifications from anon;
revoke insert,update,delete on public.billing_notifications from authenticated;
grant select on public.billing_notifications to authenticated;
drop policy if exists "Owners can read billing notifications" on public.billing_notifications;
create policy "Owners can read billing notifications" on public.billing_notifications for select to authenticated using((select auth.uid())=owner_id);
create index if not exists billing_notifications_owner_id_idx on public.billing_notifications(owner_id);
create index if not exists billing_notifications_due_idx on public.billing_notifications(status,due_at);

create or replace function private.seed_builder_billing_notifications(p_site_id uuid,p_owner_id uuid,p_failed_at timestamptz)
returns void language plpgsql security definer set search_path='' as $$
begin
 insert into public.billing_notifications(site_id,owner_id,notification_key,due_at) values
 (p_site_id,p_owner_id,'payment_failed',p_failed_at),(p_site_id,p_owner_id,'reminder_j3',p_failed_at+interval '3 days'),
 (p_site_id,p_owner_id,'reminder_j7',p_failed_at+interval '7 days'),(p_site_id,p_owner_id,'reminder_j12',p_failed_at+interval '12 days'),
 (p_site_id,p_owner_id,'retention_j74',p_failed_at+interval '74 days'),(p_site_id,p_owner_id,'retention_j97',p_failed_at+interval '97 days')
 on conflict(site_id,notification_key,due_at) do nothing;
end $$;
revoke all on function private.seed_builder_billing_notifications(uuid,uuid,timestamptz) from public,anon,authenticated;
grant execute on function private.seed_builder_billing_notifications(uuid,uuid,timestamptz) to service_role;

create or replace function private.start_builder_payment_grace(p_site_id uuid,p_owner_id uuid,p_failed_at timestamptz,p_provider_status text,p_provider_event_id text default null)
returns void language plpgsql security definer set search_path='' as $$
declare old_state text;
begin
 select state into old_state from public.site_billing_states where site_id=p_site_id;
 insert into public.site_billing_states(site_id,owner_id,state,provider_status,grace_started_at,grace_until,restricted_at,public_suspend_at,export_until,delete_after,updated_at)
 values(p_site_id,p_owner_id,'grace',p_provider_status,p_failed_at,p_failed_at+interval '14 days',p_failed_at+interval '14 days',p_failed_at+interval '28 days',p_failed_at+interval '104 days',p_failed_at+interval '104 days',now())
 on conflict(site_id) do update set owner_id=excluded.owner_id,state='grace',provider_status=excluded.provider_status,grace_started_at=excluded.grace_started_at,grace_until=excluded.grace_until,restricted_at=excluded.restricted_at,public_suspend_at=excluded.public_suspend_at,export_until=excluded.export_until,delete_after=excluded.delete_after,updated_at=now();
 update public.sites set public_access_state='live' where id=p_site_id and owner_id=p_owner_id;
 insert into public.billing_state_events(site_id,owner_id,from_state,to_state,reason,provider_event_id)
 values(p_site_id,p_owner_id,old_state,'grace','payment_failed',p_provider_event_id) on conflict(provider_event_id) do nothing;
 perform private.seed_builder_billing_notifications(p_site_id,p_owner_id,p_failed_at);
end $$;
revoke all on function private.start_builder_payment_grace(uuid,uuid,timestamptz,text,text) from public,anon,authenticated;
grant execute on function private.start_builder_payment_grace(uuid,uuid,timestamptz,text,text) to service_role;

create or replace function private.reactivate_builder_site(p_site_id uuid,p_owner_id uuid,p_paid_through timestamptz,p_provider_status text,p_provider_event_id text default null)
returns void language plpgsql security definer set search_path='' as $$
declare old_state text;
begin
 select state into old_state from public.site_billing_states where site_id=p_site_id;
 insert into public.site_billing_states(site_id,owner_id,state,provider_status,paid_through,grace_started_at,grace_until,restricted_at,public_suspend_at,export_until,delete_after,updated_at)
 values(p_site_id,p_owner_id,'active',p_provider_status,p_paid_through,null,null,null,null,null,null,now())
 on conflict(site_id) do update set state='active',provider_status=excluded.provider_status,paid_through=excluded.paid_through,grace_started_at=null,grace_until=null,restricted_at=null,public_suspend_at=null,export_until=null,delete_after=null,manual_hold_reason=null,updated_at=now();
 update public.sites set public_access_state='live' where id=p_site_id and owner_id=p_owner_id;
 update public.billing_notifications set status='canceled',updated_at=now() where site_id=p_site_id and status in ('pending','processing');
 insert into public.billing_state_events(site_id,owner_id,from_state,to_state,reason,provider_event_id)
 values(p_site_id,p_owner_id,old_state,'active','payment_recovered',p_provider_event_id) on conflict(provider_event_id) do nothing;
 insert into public.billing_notifications(site_id,owner_id,notification_key,due_at,status) values(p_site_id,p_owner_id,'reactivated',now(),'pending');
end $$;
revoke all on function private.reactivate_builder_site(uuid,uuid,timestamptz,text,text) from public,anon,authenticated;
grant execute on function private.reactivate_builder_site(uuid,uuid,timestamptz,text,text) to service_role;
