"use client";

import Link from "next/link";
import { FormEvent,useState } from "react";
import { submitFeedback,type FeedbackCategory } from "../../lib/product-analytics";
import { useProductLocale } from "../../lib/product-i18n";
import { LanguageSwitch } from "../../components/LanguageSwitch";

export default function FeedbackPage(){
 const { tr } = useProductLocale();
 const [category,setCategory]=useState<FeedbackCategory>("usability");const [rating,setRating]=useState(5);const [message,setMessage]=useState("");const [status,setStatus]=useState("");const [busy,setBusy]=useState(false);
 const send=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setStatus("");try{await submitFeedback({category,rating,message});setMessage("");setStatus(tr("Merci. Votre retour est enregistré pour la prochaine amélioration du Builder.", "Thank you. Your feedback has been recorded for the next Builder improvement."));}catch(err){setStatus(err instanceof Error?err.message:tr("Envoi impossible.", "Unable to send feedback."));}finally{setBusy(false);}};
 return <main className="plans-page"><section className="plans-hero"><div className="builder-language-row"><p className="eyebrow">AJG Beta</p><LanguageSwitch compact /></div><h1>{tr("Votre retour améliore le Builder", "Your feedback improves the Builder")}</h1><p>{tr("Décrivez ce qui vous bloque, ce qui manque ou ce qui pourrait être plus simple. Aucun historique de navigation, donnée publicitaire ou contenu du site n’est ajouté automatiquement à votre message.", "Tell us what blocks you, what is missing or what could be simpler. No browsing history, advertising data or website content is automatically added to your message.")}</p><Link className="button secondary" href="/builder">← {tr("Retour au builder", "Back to Builder")}</Link></section>
 <form className="feedback-form" onSubmit={send}><label>{tr("Type de retour", "Feedback type")}<select value={category} onChange={e=>setCategory(e.target.value as FeedbackCategory)}><option value="usability">{tr("Facilité d’utilisation", "Ease of use")}</option><option value="quality">{tr("Qualité du résultat", "Result quality")}</option><option value="bug">Bug</option><option value="idea">{tr("Idée", "Idea")}</option><option value="other">{tr("Autre", "Other")}</option></select></label><label>{tr("Note globale", "Overall rating")}<select value={rating} onChange={e=>setRating(Number(e.target.value))}>{[5,4,3,2,1].map(n=><option key={n} value={n}>{n}/5</option>)}</select></label><label className="feedback-message">{tr("Votre retour", "Your feedback")}<textarea rows={7} maxLength={2000} value={message} onChange={e=>setMessage(e.target.value)} placeholder={tr("Expliquez ce que vous essayiez de faire et ce qui vous aiderait…", "Explain what you were trying to do and what would help…")}/></label><button className="button primary" disabled={busy||message.trim().length<3}>{busy?tr("Envoi…", "Sending…"):tr("Envoyer mon retour", "Send feedback")}</button></form>{status?<p className="plans-note" role="status">{status}</p>:null}</main>;
}