"use client";

import Link from "next/link";
import { FormEvent,useState } from "react";
import { submitFeedback,type FeedbackCategory } from "../../lib/product-analytics";

export default function FeedbackPage(){
 const [category,setCategory]=useState<FeedbackCategory>("usability");const [rating,setRating]=useState(5);const [message,setMessage]=useState("");const [status,setStatus]=useState("");const [busy,setBusy]=useState(false);
 const send=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setStatus("");try{await submitFeedback({category,rating,message});setMessage("");setStatus("Merci. Votre retour est enregistré pour la prochaine amélioration du Builder.");}catch(err){setStatus(err instanceof Error?err.message:"Envoi impossible.");}finally{setBusy(false);}};
 return <main className="plans-page"><section className="plans-hero"><p className="eyebrow">Bêta AJG</p><h1>Votre retour améliore le Builder</h1><p>Décrivez ce qui vous bloque, ce qui manque ou ce qui pourrait être plus simple. Aucun historique de navigation, donnée publicitaire ou contenu du site n’est ajouté automatiquement à votre message.</p><Link className="button secondary" href="/builder">← Retour au builder</Link></section>
 <form className="feedback-form" onSubmit={send}><label>Type de retour<select value={category} onChange={e=>setCategory(e.target.value as FeedbackCategory)}><option value="usability">Facilité d’utilisation</option><option value="quality">Qualité du résultat</option><option value="bug">Bug</option><option value="idea">Idée</option><option value="other">Autre</option></select></label><label>Note globale<select value={rating} onChange={e=>setRating(Number(e.target.value))}>{[5,4,3,2,1].map(n=><option key={n} value={n}>{n}/5</option>)}</select></label><label className="feedback-message">Votre retour<textarea rows={7} maxLength={2000} value={message} onChange={e=>setMessage(e.target.value)} placeholder="Expliquez ce que vous essayiez de faire et ce qui vous aiderait…"/></label><button className="button primary" disabled={busy||message.trim().length<3}>{busy?"Envoi…":"Envoyer mon retour"}</button></form>{status?<p className="plans-note" role="status">{status}</p>:null}</main>;
}