"use client";

import type { ChangeEvent } from "react";
import type { SiteModules } from "../lib/site-design";

export default function ModulesEditor({ modules, onChange, onImage, uploading }: { modules: SiteModules; onChange: (value: SiteModules) => void; onImage: (event: ChangeEvent<HTMLInputElement>) => void; uploading: boolean }) {
  const change = <K extends keyof SiteModules>(key: K, value: SiteModules[K]) => onChange({ ...modules, [key]: value });
  return <div className="modules-editor">
    <p>Chaque rubrique apparaît uniquement si elle est activée et contient au moins un élément complet.</p>
    <section className="module-editor"><label><input type="checkbox" checked={modules.gallery.enabled} onChange={(e) => change("gallery", { ...modules.gallery, enabled: e.target.checked })} /> <b>Galerie / Voyages</b></label>
      {modules.gallery.enabled ? <div className="module-fields"><label>Titre<input value={modules.gallery.title} maxLength={100} onChange={(e) => change("gallery", { ...modules.gallery, title: e.target.value })} /></label><label>Ajouter une photo personnelle<input type="file" accept="image/jpeg,image/png,image/webp,image/avif" disabled={uploading || modules.gallery.images.length >= 12} onChange={onImage} /></label>{modules.gallery.images.map((image, index) => <div className="module-row" key={index}><img src={image.url} alt="" /><input aria-label={`Légende photo ${index + 1}`} placeholder="Légende facultative" value={image.caption} onChange={(e) => change("gallery", { ...modules.gallery, images: modules.gallery.images.map((item, i) => i === index ? { ...item, caption: e.target.value } : item) })} /><button type="button" onClick={() => change("gallery", { ...modules.gallery, images: modules.gallery.images.filter((_, i) => i !== index) })}>Retirer</button></div>)}</div> : null}
    </section>
    <section className="module-editor"><label><input type="checkbox" checked={modules.faq.enabled} onChange={(e) => change("faq", { ...modules.faq, enabled: e.target.checked })} /> <b>FAQ</b></label>{modules.faq.enabled ? <div className="module-fields"><label>Titre<input value={modules.faq.title} onChange={(e) => change("faq", { ...modules.faq, title: e.target.value })} /></label>{modules.faq.items.map((item, index) => <div className="module-item" key={index}><input placeholder="Question" aria-label={`Question ${index + 1}`} value={item.question} onChange={(e) => change("faq", { ...modules.faq, items: modules.faq.items.map((q, i) => i === index ? { ...q, question: e.target.value } : q) })} /><textarea placeholder="Réponse" aria-label={`Réponse ${index + 1}`} value={item.answer} onChange={(e) => change("faq", { ...modules.faq, items: modules.faq.items.map((q, i) => i === index ? { ...q, answer: e.target.value } : q) })} /><button type="button" onClick={() => change("faq", { ...modules.faq, items: modules.faq.items.filter((_, i) => i !== index) })}>Retirer</button></div>)}<button type="button" className="secondary" disabled={modules.faq.items.length >= 12} onClick={() => change("faq", { ...modules.faq, items: [...modules.faq.items, { question: "", answer: "" }] })}>Ajouter une question</button></div> : null}</section>
    <section className="module-editor"><label><input type="checkbox" checked={modules.testimonials.enabled} onChange={(e) => change("testimonials", { ...modules.testimonials, enabled: e.target.checked })} /> <b>Témoignages</b></label>{modules.testimonials.enabled ? <div className="module-fields"><label>Titre<input value={modules.testimonials.title} onChange={(e) => change("testimonials", { ...modules.testimonials, title: e.target.value })} /></label>{modules.testimonials.items.map((item, index) => <div className="module-item" key={index}><textarea placeholder="Témoignage obtenu avec accord de publication" aria-label={`Témoignage ${index + 1}`} value={item.quote} onChange={(e) => change("testimonials", { ...modules.testimonials, items: modules.testimonials.items.map((q, i) => i === index ? { ...q, quote: e.target.value } : q) })} /><input placeholder="Prénom ou attribution autorisée" aria-label={`Auteur ${index + 1}`} value={item.author} onChange={(e) => change("testimonials", { ...modules.testimonials, items: modules.testimonials.items.map((q, i) => i === index ? { ...q, author: e.target.value } : q) })} /><button type="button" onClick={() => change("testimonials", { ...modules.testimonials, items: modules.testimonials.items.filter((_, i) => i !== index) })}>Retirer</button></div>)}<button type="button" className="secondary" disabled={modules.testimonials.items.length >= 12} onClick={() => change("testimonials", { ...modules.testimonials, items: [...modules.testimonials.items, { quote: "", author: "" }] })}>Ajouter un témoignage</button></div> : null}</section>
    <section className="module-editor"><label><input type="checkbox" checked={modules.contact.enabled} onChange={(e) => change("contact", { ...modules.contact, enabled: e.target.checked })} /> <b>Contact</b></label>{modules.contact.enabled ? <div className="module-fields"><label>Titre<input value={modules.contact.title} onChange={(e) => change("contact", { ...modules.contact, title: e.target.value })} /></label><label>Adresse e-mail publique<input type="email" value={modules.contact.email} onChange={(e) => change("contact", { ...modules.contact, email: e.target.value })} /></label><small>Le bouton ouvre la messagerie du visiteur ; votre adresse sera visible publiquement.</small></div> : null}</section>
  </div>;
}
