create table if not exists public.builder_e2e_runs (
  id bigint generated by default as identity primary key,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  locale text not null check (locale in ('fr','en')),
  include_ai boolean not null default false,
  deployment_sha text,
  status text not null default 'running'
    check (status in ('running','success','failed','cleanup_failed')),
  failure_stage text,
  detail text,
  steps jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists builder_e2e_runs_release_idx
  on public.builder_e2e_runs(deployment_sha, locale, include_ai, status, completed_at desc nulls last);

create index if not exists builder_e2e_runs_completed_idx
  on public.builder_e2e_runs(completed_at desc nulls last);

alter table public.builder_e2e_runs enable row level security;

revoke all on public.builder_e2e_runs from anon, authenticated;
grant select, insert, update, delete on public.builder_e2e_runs to service_role;
