create table if not exists public.beta_operations_runs (
  id bigint generated by default as identity primary key,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  status text not null default 'running'
    check (status in ('running','healthy','attention','failed')),
  scanned_users integer not null default 0 check (scanned_users >= 0),
  grant_count integer not null default 0 check (grant_count >= 0),
  active_tester_count integer not null default 0 check (active_tester_count >= 0),
  repaired_metadata integer not null default 0 check (repaired_metadata >= 0),
  revoked_stale_metadata integer not null default 0 check (revoked_stale_metadata >= 0),
  repair_failures integer not null default 0 check (repair_failures >= 0),
  follow_up_candidates integer not null default 0 check (follow_up_candidates >= 0),
  awaiting_resume integer not null default 0 check (awaiting_resume >= 0),
  unresponsive_after_followup integer not null default 0 check (unresponsive_after_followup >= 0),
  completed_missions integer not null default 0 check (completed_missions >= 0),
  errors jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists beta_operations_runs_completed_idx
  on public.beta_operations_runs(completed_at desc nulls last);

create index if not exists beta_operations_runs_status_idx
  on public.beta_operations_runs(status, completed_at desc nulls last);

alter table public.beta_operations_runs enable row level security;

revoke all on public.beta_operations_runs from anon, authenticated;
grant select, insert, update, delete on public.beta_operations_runs to service_role;
