create table if not exists public.support_operations_runs (
  id bigint generated by default as identity primary key,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  status text not null default 'running'
    check (status in ('running','healthy','attention','failed')),
  reconcile_scanned integer not null default 0 check (reconcile_scanned >= 0),
  reconcile_resolved integer not null default 0 check (reconcile_resolved >= 0),
  reconcile_escalated integer not null default 0 check (reconcile_escalated >= 0),
  reconcile_waiting integer not null default 0 check (reconcile_waiting >= 0),
  reconcile_failed integer not null default 0 check (reconcile_failed >= 0),
  remediation_scanned integer not null default 0 check (remediation_scanned >= 0),
  remediation_eligible integer not null default 0 check (remediation_eligible >= 0),
  remediation_attempted integer not null default 0 check (remediation_attempted >= 0),
  remediation_succeeded integer not null default 0 check (remediation_succeeded >= 0),
  remediation_no_change integer not null default 0 check (remediation_no_change >= 0),
  remediation_failed integer not null default 0 check (remediation_failed >= 0),
  runtime_status text not null default 'unknown'
    check (runtime_status in ('healthy','warning','incident','unknown')),
  runtime_error_count integer not null default 0 check (runtime_error_count >= 0),
  runtime_fatal_count integer not null default 0 check (runtime_fatal_count >= 0),
  runtime_http5xx_count integer not null default 0 check (runtime_http5xx_count >= 0),
  runtime_deployment_id text,
  reported_to_run boolean not null default false,
  report_reason text,
  errors jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists support_operations_runs_completed_idx
  on public.support_operations_runs(completed_at desc nulls last);
create index if not exists support_operations_runs_status_idx
  on public.support_operations_runs(status, completed_at desc nulls last);

alter table public.support_operations_runs enable row level security;
revoke all on public.support_operations_runs from anon, authenticated;
grant select, insert, update, delete on public.support_operations_runs to service_role;
