create table if not exists public.release_visual_reviews (
  id bigint generated by default as identity primary key,
  deployment_sha text not null,
  locale text not null check (locale in ('fr','en')),
  viewport text not null check (viewport in ('desktop','mobile')),
  surface_set_version text not null default 'customer-core-v1',
  approved boolean not null,
  reviewed_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (deployment_sha, locale, viewport, surface_set_version)
);

create index if not exists release_visual_reviews_sha_idx
  on public.release_visual_reviews(deployment_sha, surface_set_version, approved, reviewed_at desc);

alter table public.release_visual_reviews enable row level security;
revoke all on public.release_visual_reviews from anon, authenticated;
grant select, insert, update, delete on public.release_visual_reviews to service_role;
